redis:
    image: redis
    container_name: cache
    expose:
      - 6379
app:
    build: ./
    volumes:
        - ./:/var/www/app
    links:
        - redis
    ports:
        - 3000:3000
    environment:
        - REDIS_ENV=redis
        - NODE_ENV=development
        - PORT=3000
    command:
        sh -c 'yarn dev:server'